#! /bin/sh

# colors (copied from .Xresources)
FG='#a8a19f'
BG='#1b1918'
GREEN='#5ab738'

# monitor setup
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
. /home/filipe/.config/bspwm/multimonitor.sh

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config pointer_follows_monitor true

bspc config automatic_scheme alternate

bspc config normal_border_color     $BG
bspc config active_border_color     $FG
bspc config focused_border_color    $GREEN
bspc config presel_feedback_color   $GREEN

# browsers
bspc rule -a Chromium desktop='^7'
bspc rule -a Firefox desktop='^7'
bspc rule -a qutebrowser desktop='^7'

bspc rule -a Slack desktop='^6'
bspc rule -a Screenkey manage=off

# floating stuff
bspc rule -a confirm state=floating
bspc rule -a dialog state=floating
bspc rule -a download state=floating
bspc rule -a error state=floating
bspc rule -a file_progress state=floating
bspc rule -a notification state=floating
bspc rule -a splash state=floating
bspc rule -a toolbar state=floating
bspc rule -a pinentry state=floating
bspc rule -a simplescreenrecorder state=floating
bspc rule -a ghb state=floating     # Handbrake
bspc rule -a nm-connection-editor state=floating
bspc rule -a pritunl state=floating
bspc rule -a zoom state=floating
bspc rule -a keybase state=floating

# launch polybar
/home/filipe/.config/polybar/launch.sh
